# Generated by Django 4.2.1 on 2023-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timereg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('estimated_production_time', models.DurationField()),
                ('actual_production_time', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='actual_production_time',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='estimated_production_time',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='production_id',
        ),
        migrations.AddField(
            model_name='productionline',
            name='description_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productionline',
            name='productionline_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
