# Generated by Django 4.2.1 on 2023-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timereg', '0003_alter_productionline_productionline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontime',
            name='variation_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
