# Generated by Django 4.2.1 on 2023-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timereg', '0004_productiontime_variation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontime',
            name='variation_time',
            field=models.DurationField(null=True),
        ),
    ]
