# Generated by Django 4.2.1 on 2023-05-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timereg', '0006_alter_productiontime_variation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
