# Generated by Django 4.2.1 on 2023-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timereg', '0009_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='completed',
            field=models.BinaryField(default=False, null=True),
        ),
    ]
