# Generated by Django 4.2.1 on 2023-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timereg', '0010_worktime_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
