# Generated by Django 4.1.3 on 2023-06-15 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("timereg", "0011_alter_worktime_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="productiontime",
            name="production_line",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="timereg.productionline",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productiontime",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
