# Generated by Django 4.1.3 on 2023-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timereg", "0012_productiontime_production_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productiontime",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
