# Generated by Django 4.1.3 on 2023-06-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timereg", "0013_alter_productiontime_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productiontime",
            name="actual_production_time",
            field=models.DurationField(null=True),
        ),
    ]
