# Generated by Django 4.1.3 on 2023-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timereg", "0014_alter_productiontime_actual_production_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productiontime",
            name="actual_production_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
